version: "3.8"

networks:
  custom_network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: movie_website
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      custom_network:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_container
    restart: always
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=192.168.1.120
    ports:
      - "8080:8080"
    volumes:
      - "D:/keycloak-data:/opt/keycloak/data"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      custom_network:

  minio:
    image: minio/minio
    container_name: minio_container
    restart: always
    command: server --console-address ":9001" /data
    environment:
      MINIO_ACCESS_KEY: ROOTUSER
      MINIO_SECRET_KEY: CHANGEME@123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      custom_network:

  webapp:
    build: .
    container_name: springboot_app
    restart: always
    environment:
      ISSUER_URI: http://keycloak:8080/realms/movie_website_realm
      JWK_SET_URI: http://keycloak:8080/realms/movie_website_realm/protocol/openid-connect/certs
      SERVER_PORT: 8081
      DATABASE_URL: jdbc:mysql://mysql:3306/movie_website
      DATABASE_USER: keycloak_user
      DATABASE_PASSWORD: keycloak_pass
      MYSQL_DATABASE: movie_website
      MINIO_FILE_HOST: http://minio:9001
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ROOTUSER
      MINIO_SECRET_KEY: CHANGEME@123
      KEYCLOAK_URI: http://keycloak:8080
      PROFILE_REALM: movie_website_realm
      MOVIE_CLIENT_ID: movie_website_client
      MOVIE_CLIENT_SECRET: ryBcX7pKONjVb57gVK6UYOmlU9qQ1edA
      VIDEO_TOKEN_SECRET: jwtR2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWnZr4u7w!z%C*F-JaNd
      VIDEO_TOKEN_VALIDITY: 7200000
      RATE_LIMIT_MAX_REQUESTS: 100
      RATE_LIMIT_TIME_WINDOW: 3600000
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_started
      minio:
        condition: service_started
    networks:
      custom_network:

volumes:
  mysql_data:
  minio_data:
  keycloak_data:


    
