version: "3.8"

networks:
  custom_network:
    driver: bridge

services:
  mysql:
    image: mysql:9.2.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: movie_website
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_pass
    ports:
      - "3307:3306"
    volumes:
      - "D:/docker/mysql/volume:/var/lib/mysql"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    networks:
      custom_network:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_container
    restart: always
    command:
      start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=192.168.1.120
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_COOKIE_SECURE=true
    ports:
      - "8080:8080"
    volumes:
      - "D:/docker/keycloak/volume:/opt/keycloak/data"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      custom_network:

  minio:
    image: minio/minio
    container_name: minio_container
    restart: always
    command: server --console-address ":9001" /data
    environment:
      MINIO_ACCESS_KEY: ROOTUSER
      MINIO_SECRET_KEY: CHANGEME@123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "D:/docker/minio/volume:/data"
    networks:
      custom_network:

  webapp:
    build: .
    container_name: springboot_app
    restart: always
    environment:
      SERVER_PORT: 8081
      DATABASE_URL: jdbc:mysql://mysql:3306/movie_website
      DATABASE_USER: root
      DATABASE_PASSWORD: 1234
      MYSQL_DATABASE: movie_website
      # KEYCLOAK
      ISSUER_URI: http://192.168.1.120:8080/realms/movie_website_realm
      JWK_SET_URI: http://192.168.1.120:8080/realms/movie_website_realm/protocol/openid-connect/certs
      # MINIO
      MINIO_FILE_HOST: http://192.168.1.120:9001
      MINIO_ENDPOINT: http://192.168.1.120:9000
      MINIO_ACCESS_KEY: ROOTUSER
      MINIO_SECRET_KEY: CHANGEME@123
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_started
      minio:
        condition: service_started
    networks:
      custom_network:

volumes:
  mysql_data:
  minio_data:
  keycloak_data:


    
