server:
  port: ${SERVER_PORT:8081}
error:
  include-binding-errors: always
spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/movie_website_realm
          jwk-set-uri: http://localhost:8080/realms/movie_website_realm/protocol/openid-connect/certs
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  application:
    name: electronic_device_shop
  profiles:
    active: ${ENV:dev}
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/movie_website}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: hikari-id
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 20
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: false
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

minio:
  endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}
  fileHost: ${MINIO_FILE_HOST:http://127.0.0.1:9001}
  expiredDefault: ${EXPIRED:60}

common:
  permit-all-path-patterns:
    - /swagger-ui.html/**
    - /v3/api-docs/**
    - /swagger-ui/**
    - /api/account/register
    - /api/account/getListUser
    - /api/account/login
    - /api/v1/movies/**
    - /api/v1/categories/list
    - /api/v1/genre/**
    - /api/v1/evaluations/average/**
    - /api/v1/evaluations/numberOfReviews/**
    - /api/account/info/**
    - /api/v1/evaluations/numberOfReviews/**
    - /api/v1/minio/video/**

  cors:
    origins:
      - http://localhost:8081
      - http://localhost:3000

keycloak:
  auth-server-url: ${KEYCLOAK_URI:http://localhost:8080}
  realm: ${PROFILE_REALM:movie_website_realm}
  resource: ${MOVIE_CLIENT_ID:movie_website_client}
  credentials:
    secret: ${MOVIE_CLIENT_SECRET:ryBcX7pKONjVb57gVK6UYOmlU9qQ1edA}
